version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # ports:
    # - "${BACKEND_PORT}:8080"   
    environment:
      - DATABASE_DSN=gorm:gorm@tcp(db:3306)/gorm?charset=utf8&parseTime=True&loc=Local
    depends_on:
      - db
    networks:
      - tinker-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # ports:
    # - "${FRONTEND_PORT}:80"   
    depends_on:
      - backend
    networks:
      - tinker-net

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: gorm
      MYSQL_USER: gorm
      MYSQL_PASSWORD: gorm
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    # ports:
      # - "${DB_PORT}:3306"
    networks:
      - tinker-net


volumes:
  db-data:

networks:
  tinker-net:
    external: true
